title: "<h2><span style='color:#fefcef ;'>Aakanksha Dutta</span></h2>"

# Description section with timeline-like experience format
description: > 
  <div style="color: #222 ;"> <!-- Set the body text color -->
    Welcome to my portfolio page, where I share projects that blend creativity and data to solve real-world challenges. Explore my work and feel free to connect! 
    <br><br>
   
    <div style="color: #222 ;font-family: Arial, sans-serif; max-width: 800px; margin: auto;">
    
    <!-- Experience 1 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Aug 2025 - Present</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Science Intern</div>
      <div style="font-size: 0.9em;">KCC Capital Partners</div>
    </div>
    
    <!-- Experience 2 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Jun 2024 - Aug 2024</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Analyst Intern</div>
      <div style="font-size: 0.9em;">Next Step Projects</div>
    </div>
  
    <!-- Experience 3 -->
    <div style="padding: 10px 0; position: relative; ">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Apr 2024 - Jun 2024</div>
      <div style="font-weight: bold; font-size: 1.1em;">Project Lead & Financial Data Analyst </div>
      <div style="font-size: 0.9em;">Sumzero</div>
    </div>

        <!-- Experience 4 -->
    <div style="padding: 10px 0; position: relative; ">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Aug 2023 - Sep 2023</div>
      <div style="font-weight: bold; font-size: 1.1em;">Quantitative Analyst </div>
      <div style="font-size: 0.9em;">Chapman Office</div>
    </div>
  
    <!-- Experience 5 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Jan 2023 - Aug 2023</div>
      <div style="font-weight: bold; font-size: 1.1em;">Sales Operations Analyst </div>
      <div style="font-size: 0.9em;">Arcserve Ltd.</div>
    </div>

    <!-- Experience 6 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #2774ae; font-size: 0.85em;">Oct 2022 - Jan 2023</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Analyst</div>
      <div style="font-size: 0.9em;"> Teleperformance Ltd.</div>
    </div>

  </div>

  
  <style>
   /* Timeline container */
   .timeline-container {
      position: relative;
      margin: 5px 0;
      padding: 5px 0;
   }

   

   /* Timeline item */
   .timeline-item {
      position: relative;
      margin: 0;
      width: 50%;
   }


   /* Left-side content */
   .timeline-item.left {
      left: 0;
   }

   /* Right-side content */
   .timeline-item.right {
      left: 50%;
   }

   

   /* Adjust content positioning (distance of the text from the center line) */
   .timeline-item.left .timeline-content {
      text-align: right;
      margin-right: 20px;
   }

   .timeline-item.right .timeline-content {
      text-align: left;
      margin-left: 20px;
   }

   /* Date styling */
   .timeline-date {
      font-size: 16px;
      font-weight: bold;
      color: #ECE99B;
      margin-bottom: 0;
   }
  </style>

  
    <a href="https://www.linkedin.com/in/aakanksha-dutta/" target="_blank" style="color:#2774ae ;">
      <img src="images/icons8-linkedin-50.png" alt="LinkedIn">
      View My LinkedIn
    </a>
    <br><br>
    <a href="https://medium.com/@aakanksha.dutta4" target="_blank" style="color:#2774ae ;">
      <img src="images/icons8-medium-monogram-64.png" alt="Medium">
      Visit My Medium
    </a>
  </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
